{{- if .Values.nodeComponentsCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kvisor.nodeComponentsCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kvisor.nodeComponentsCollector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kvisor.nodeComponentsCollector.fullname" . }}
  labels:
    {{- include "kvisor.nodeComponentsCollector.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kvisor.nodeComponentsCollector.fullname" . }}
  labels:
    {{- include "kvisor.nodeComponentsCollector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kvisor.nodeComponentsCollector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kvisor.nodeComponentsCollector.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
{{- end }}
